basePath: /api
definitions:
  base.AssignUsersReq:
    properties:
      role_id:
        type: integer
      user_ids:
        items:
          type: integer
        type: array
    type: object
  base.AssignUsersResp:
    type: object
  base.CreateMenuReq:
    properties:
      icon:
        type: string
      name:
        type: string
      parent_id:
        type: integer
      path:
        type: string
      sort:
        type: integer
      status:
        type: integer
      type:
        type: integer
    type: object
  base.CreateMenuResp:
    properties:
      id:
        type: integer
    type: object
  base.CreateRoleReq:
    properties:
      description:
        type: string
      menu_ids:
        items:
          type: integer
        type: array
      name:
        type: string
      status:
        type: integer
    type: object
  base.CreateRoleResp:
    properties:
      id:
        type: integer
    type: object
  base.CreateSysUserReq:
    properties:
      avatar:
        type: string
      nick_name:
        type: string
      password:
        type: string
      phone:
        type: string
      status:
        type: integer
      user_name:
        type: string
    type: object
  base.CreateSysUserResp:
    type: object
  base.DeleteMenuReq:
    properties:
      id:
        type: integer
    type: object
  base.DeleteMenuResp:
    type: object
  base.DeleteRoleReq:
    properties:
      id:
        type: integer
    type: object
  base.DeleteRoleResp:
    type: object
  base.DeleteSysUserReq:
    properties:
      id:
        type: integer
    type: object
  base.DeleteSysUserResp:
    type: object
  base.GetMenuTreeReq:
    type: object
  base.GetMenuTreeResp:
    properties:
      list:
        items:
          $ref: '#/definitions/base.MenuTreeNode'
        type: array
    type: object
  base.GetRoleListReq:
    properties:
      name:
        type: string
      page:
        type: integer
      page_size:
        type: integer
      status:
        type: integer
    type: object
  base.GetRoleListResp:
    properties:
      list:
        items:
          $ref: '#/definitions/base.RoleInfo'
        type: array
      total:
        type: integer
    type: object
  base.GetSysUserListReq:
    properties:
      page:
        type: integer
      page_size:
        type: integer
      phone:
        type: string
      status:
        type: integer
      user_name:
        type: string
    type: object
  base.GetSysUserListResp:
    properties:
      list:
        items:
          $ref: '#/definitions/base.SysUserInfo'
        type: array
      total:
        type: integer
    type: object
  base.GetUserInfoReq:
    type: object
  base.GetUserInfoResp:
    properties:
      user_info:
        $ref: '#/definitions/base.UserInfo'
    type: object
  base.GetUserMenuReq:
    type: object
  base.GetUserMenuResp:
    properties:
      list:
        items:
          $ref: '#/definitions/base.MenuTreeNode'
        type: array
    type: object
  base.LoginParams:
    properties:
      password:
        type: string
      user_name:
        type: string
    type: object
  base.LoginResp:
    properties:
      token:
        type: string
    type: object
  base.MenuSort:
    properties:
      id:
        type: integer
      parent_id:
        type: integer
      sequence:
        type: integer
    type: object
  base.MenuTreeNode:
    properties:
      children:
        items:
          $ref: '#/definitions/base.MenuTreeNode'
        type: array
      icon:
        type: string
      id:
        type: integer
      name:
        type: string
      parent_id:
        type: integer
      path:
        type: string
      sort:
        type: integer
      status:
        type: integer
      type:
        type: integer
    type: object
  base.RoleInfo:
    properties:
      created_at:
        type: integer
      description:
        type: string
      id:
        type: integer
      menu_ids:
        items:
          type: integer
        type: array
      name:
        type: string
      status:
        type: integer
      updated_at:
        type: integer
      user_ids:
        items:
          type: integer
        type: array
    type: object
  base.SortMenuReq:
    properties:
      list:
        items:
          $ref: '#/definitions/base.MenuSort'
        type: array
    type: object
  base.SortMenuResp:
    type: object
  base.SysUserInfo:
    properties:
      avatar:
        type: string
      created_at:
        type: integer
      id:
        type: integer
      nick_name:
        type: string
      phone:
        type: string
      status:
        type: integer
      updated_at:
        type: integer
      user_name:
        type: string
    type: object
  base.UpdateMenuReq:
    properties:
      icon:
        type: string
      id:
        type: integer
      name:
        type: string
      parent_id:
        type: integer
      path:
        type: string
      sort:
        type: integer
      status:
        type: integer
      type:
        type: integer
    type: object
  base.UpdateMenuResp:
    type: object
  base.UpdateRoleReq:
    properties:
      description:
        type: string
      id:
        type: integer
      menu_ids:
        items:
          type: integer
        type: array
      name:
        type: string
      status:
        type: integer
    type: object
  base.UpdateRoleResp:
    type: object
  base.UpdateSysUserReq:
    properties:
      avatar:
        type: string
      id:
        type: integer
      nick_name:
        type: string
      phone:
        type: string
      status:
        type: integer
    type: object
  base.UpdateSysUserResp:
    type: object
  base.UserInfo:
    properties:
      avatar:
        type: string
      id:
        type: integer
      nick_name:
        type: string
      phone:
        type: string
      status:
        type: integer
      user_name:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Your API Description
  title: Your API Title
  version: "1.0"
paths:
  /api/login:
    post:
      description: 用户登录接口
      parameters:
      - description: json入参
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/base.LoginParams'
      responses:
        "200":
          description: 返回值
          schema:
            $ref: '#/definitions/base.LoginResp'
      summary: 用户登录
      tags:
      - 系统认证
  /api/sys_menu/create:
    post:
      description: 创建系统菜单
      parameters:
      - description: json入参
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/base.CreateMenuReq'
      responses:
        "200":
          description: 返回值
          schema:
            $ref: '#/definitions/base.CreateMenuResp'
      summary: 创建菜单
      tags:
      - 系统菜单管理
  /api/sys_menu/delete:
    delete:
      description: 删除系统菜单
      parameters:
      - description: json入参
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/base.DeleteMenuReq'
      responses:
        "200":
          description: 返回值
          schema:
            $ref: '#/definitions/base.DeleteMenuResp'
      summary: 删除菜单
      tags:
      - 系统菜单管理
  /api/sys_menu/search:
    get:
      description: 获取系统菜单树形结构
      parameters:
      - description: json入参
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/base.GetMenuTreeReq'
      responses:
        "200":
          description: 返回值
          schema:
            $ref: '#/definitions/base.GetMenuTreeResp'
      summary: 获取菜单树
      tags:
      - 系统菜单管理
  /api/sys_menu/sort:
    put:
      description: 对系统菜单进行排序
      parameters:
      - description: json入参
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/base.SortMenuReq'
      responses:
        "200":
          description: 返回值
          schema:
            $ref: '#/definitions/base.SortMenuResp'
      summary: 菜单排序
      tags:
      - 系统菜单管理
  /api/sys_menu/update:
    put:
      description: 更新系统菜单
      parameters:
      - description: json入参
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/base.UpdateMenuReq'
      responses:
        "200":
          description: 返回值
          schema:
            $ref: '#/definitions/base.UpdateMenuResp'
      summary: 更新菜单
      tags:
      - 系统菜单管理
  /api/sys_role:
    delete:
      description: 删除系统角色
      parameters:
      - description: json入参
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/base.DeleteRoleReq'
      responses:
        "200":
          description: 返回值
          schema:
            $ref: '#/definitions/base.DeleteRoleResp'
      summary: 删除角色
      tags:
      - 角色管理
    post:
      description: 创建系统角色
      parameters:
      - description: json入参
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/base.CreateRoleReq'
      responses:
        "200":
          description: 返回值
          schema:
            $ref: '#/definitions/base.CreateRoleResp'
      summary: 创建角色
      tags:
      - 角色管理
    put:
      description: 更新系统角色
      parameters:
      - description: json入参
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/base.UpdateRoleReq'
      responses:
        "200":
          description: 返回值
          schema:
            $ref: '#/definitions/base.UpdateRoleResp'
      summary: 更新角色
      tags:
      - 角色管理
  /api/sys_role/assign_users:
    post:
      description: 为角色分配用户
      parameters:
      - description: json入参
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/base.AssignUsersReq'
      responses:
        "200":
          description: 返回值
          schema:
            $ref: '#/definitions/base.AssignUsersResp'
      summary: 分配用户
      tags:
      - 角色管理
  /api/sys_role/search:
    post:
      description: 获取系统角色列表
      parameters:
      - description: json入参
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/base.GetRoleListReq'
      responses:
        "200":
          description: 返回值
          schema:
            $ref: '#/definitions/base.GetRoleListResp'
      summary: 获取角色列表
      tags:
      - 角色管理
  /api/sys_user/create:
    post:
      description: 创建系统用户
      parameters:
      - description: json入参
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/base.CreateSysUserReq'
      responses:
        "200":
          description: 返回值
          schema:
            $ref: '#/definitions/base.CreateSysUserResp'
      summary: 创建用户
      tags:
      - 系统用户管理
  /api/sys_user/delete:
    delete:
      description: 删除系统用户
      parameters:
      - description: json入参
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/base.DeleteSysUserReq'
      responses:
        "200":
          description: 返回值
          schema:
            $ref: '#/definitions/base.DeleteSysUserResp'
      summary: 删除用户
      tags:
      - 系统用户管理
  /api/sys_user/search:
    post:
      description: 获取系统用户列表
      parameters:
      - description: json入参
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/base.GetSysUserListReq'
      responses:
        "200":
          description: 返回值
          schema:
            $ref: '#/definitions/base.GetSysUserListResp'
      summary: 获取用户列表
      tags:
      - 系统用户管理
  /api/sys_user/update:
    put:
      description: 更新系统用户
      parameters:
      - description: json入参
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/base.UpdateSysUserReq'
      responses:
        "200":
          description: 返回值
          schema:
            $ref: '#/definitions/base.UpdateSysUserResp'
      summary: 更新用户
      tags:
      - 系统用户管理
  /api/user/info:
    get:
      description: 获取当前登录用户的信息
      parameters:
      - description: json入参
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/base.GetUserInfoReq'
      responses:
        "200":
          description: 返回值
          schema:
            $ref: '#/definitions/base.GetUserInfoResp'
      summary: 获取用户信息
      tags:
      - 系统认证
  /api/user/menu:
    get:
      description: 获取当前登录用户的菜单列表
      parameters:
      - description: json入参
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/base.GetUserMenuReq'
      responses:
        "200":
          description: 返回值
          schema:
            $ref: '#/definitions/base.GetUserMenuResp'
      summary: 获取用户菜单
      tags:
      - 系统认证
swagger: "2.0"
